bands/urls.py
from django.urls import path
from .views import *

app_name = "bands"


urlpatterns = [
    path('', band_list, name='band_list'),

    path('recurso/', band_list_recurso, name='band_list_recurso'),

    path('musics/json/', musicsJson, name='musicsJson'),

    path('<int:band_id>/', band_detail, name='band_detail'),

    path('add_band/', add_band, name='add_band_form'),
    path('<int:band_id>/add_album/', add_album, name='add_album_form'),

    path('album/<int:album_id>/', album_detail, name='album_detail'),

    path('album/<int:album_id>/add_music/', add_music, name='add_music'),

    path('music/<int:music_id>/', music_detail, name='music_detail'),
]

jornalOnline/urls.py
from django.urls import path
from . import views

app_name = 'jornalOnline'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('article/<int:article_id>/add-comment/', views.add_comment, name='add_comment'),
    path('article/<int:article_id>/add-rating/', views.add_rating, name='add_rating'),
    path('article/<int:article_id>/', views.article_detail, name='article_detail'),
    path('article/add/', views.add_article, name='add_article'),


]

meteo/urls.py
from django.urls import path
from . import views

app_name = "meteo"

urlpatterns = [


    path('previsao/', views.cidades, name='previsao'),
    path('previsao/json/', views.cidadesJson, name='previsaoJson'),


]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.portfolio_view, name="portfolio"),

    path('contacto/', views.contacto_view, name="contacto"),

    path('pw/', views.programacaoWeb, name="pwView"),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('registo/', views.registo_view, name="registo"),

    path('user/', views.user_view, name="userView"),
    path('autenticacao/login/', views.user_view),

    path('subject/<int:subjectId>/', views.subject_view, name="subjectView"), #href="{% url 'subjectView' cadeira.id %}"


]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('meteo/', include('meteo.urls')),

    path('bands/', include('bands.urls')),

    path('', include('portfolio.urls'), name='portfolio'),

    path('accounts/', include('allauth.urls')),

    path('jornalOnline/', include('jornalOnline.urls')),

]

portfolio/models.py
from django.db import models
from embed_video.fields import EmbedVideoField

class Videos(models.Model):
    video = EmbedVideoField()  # same like models.URLField()


class Teacher(models.Model):
    name = models.CharField(max_length = 200)
    linkedinLink = models.URLField(max_length = 300, blank = True)

    def __str__(self):
        return f'{self.name}'

class Concept(models.Model):
    name = models.TextField(max_length = 50)
    description = models.TextField(blank = True)

    def __str__(self):
        return f'{self.name}'

class ScientificArea(models.Model):
    name = models.CharField(max_length = 200)

    def __str__(self):
        return f'{self.name}'

class Project(models.Model):
    projectImage = models.ImageField(upload_to = 'projeto/projectImage/', blank = True)
    name = models.CharField(max_length = 200)
    description = models.TextField(blank = True)
    conceitosAplicados = models.ManyToManyField(Concept, related_name='ProjectConcepts', blank = True)
    youtubeVideo = models.URLField(max_length = 300, blank = True)
    gitHub = models.URLField(max_length = 300, blank = True)

    def __str__(self):
        return f'{self.name}'

class Course(models.Model):
    name = models.CharField(max_length = 50)
    apresentation = models.TextField(blank = True)
    conceitosAplicados = models.ManyToManyField(Concept, related_name='CourseConcepts', blank = True)

    bachelor = 1
    master = 2
    phd = 3

    choices = [
        (bachelor, "Bachelor's Degree"),
        (master, "Master's Degree"),
        (phd, "PhD")
    ]
    courseType = models.IntegerField(choices = choices, default = bachelor)

    def __str__(self):
        return f'{self.name}'

class Subject(models.Model):
    name = models.CharField(max_length = 300)#
    teacher = models.ManyToManyField(Teacher, related_name='SubjectTeacher')#
    project = models.ForeignKey(Project, on_delete=models.CASCADE, blank = True, null = True)#
    apresentacao = models.TextField(blank = True)#
    programa = models.ManyToManyField(Concept, related_name='Programa')#
    curricularIUnitReadableCode = models.CharField(max_length = 300, blank = True)#
    scientificArea = models.ForeignKey(ScientificArea, on_delete=models.CASCADE, blank = True, null = True)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, blank = True, null = True)
    ects = models.IntegerField(null=True)#
    year = models.IntegerField()#

    firstSemester = 1
    secondSemester = 2
    semester_choices = [
        (firstSemester, "1st Semester"),
        (secondSemester, "2nd Semester"),
    ]
    semester = models.IntegerField(choices=semester_choices, default=1)

    nota = models.IntegerField(default = 0)#

    def __str__(self):
        return f'{self.name}'

portfolio/forms.py
from django import forms
from django.contrib.auth.models import User

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            self.add_error('password_confirm', "Passwords do not match")
        return cleaned_data

class ContactForm(forms.Form):
    name = forms.CharField(
        required=True,
        max_length=100,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': ''})
    )
    email = forms.EmailField(
        required=True,
        max_length=100,
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': ''})
    )
    text = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control', 'placeholder': ''})
    )

portfolio/views.py
from django.shortcuts import render
from .models import *
from datetime import datetime
from django.shortcuts import render, redirect
from .utils import divide_subjects_byYear
from django.contrib.auth import models,login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.models import User
from .forms import *
from django.core.mail import send_mail

'''
Função geral para rederização de todas as páginas ------------------------------
'''
def contextFun(request):
    username = request.user.username if request.user.is_authenticated else 'Guest'
    videos = Videos.objects.all()


    context = {
        'anoAtual' : datetime.today().year,
        'username': username,
        'videos': videos,

    }

    return context

'''
Login views --------------------------------------------------------------------
'''
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"You are now logged in as {username}.")
                return redirect('portfolio:portfolio')  # Redirect to a homepage or dashboard
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    else:
        form = AuthenticationForm()

    context = contextFun(request)
    context['form'] = 'form'

    return render(request, 'auth/login.html', context)


def user_view(request):
    context = contextFun(request)
    return render(request, 'auth/user.html', context)



def logout_view(request):
    logout(request)
    return redirect('portfolio:portfolio')


def registo_view(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():

            User.objects.create_user(
                username=form.cleaned_data['username'],
                email=form.cleaned_data['email'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                password=form.cleaned_data['password']
            )
            messages.success(request, "User registered successfully.")
            return redirect('portfolio:login')
        else:
            messages.error(request, "There was an error with your registration.")
    else:
        form = UserRegistrationForm()

    context = contextFun(request)
    context['form'] = form

    return render(request, 'auth/registo.html', context)

'''
Website views ------------------------------------------------------------------
'''

def portfolio_view(request):
    curso = Course.objects.get(name="Engenharia Informática")

    context = contextFun(request)
    context['subjects'] = Subject.objects.all()
    context['curso'] = curso

    return render(request, "portfolio/portfolio.html", context)

def contacto_view(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            text = form.cleaned_data['text']

            # Sending the email
            send_mail(
                subject=f'{name}, confirmação de pedido de contacto',
                message= f'{name}, obrigado pelo contacto. Falaremos em breve.',
                from_email='duartechen@gmail.com',
                recipient_list=[email],
                fail_silently=False,
            )

            send_mail(
                subject=f'Pedido de contacto de {name}',
                message= f'{email} - {text}',
                from_email='duartechen@gmail.com',
                recipient_list=['duartechen@gmail.com'],
                fail_silently=False,
            )

            return redirect('portfolio:portfolio')
    else:
        form = ContactForm()

    context = contextFun(request)
    context['form'] = form

    return render(request, "portfolio/contacto.html", context)


def aboutMe_view(request):

    context = contextFun(request)

    return render(request, "portfolio/aboutme.html", context)

def subject_view(request, subjectId):

    context = contextFun(request)
    context['subject'] = Subject.objects.get(id=subjectId)

    return render(request, "portfolio/subject.html", context)


def programacaoWeb(request):


    context = contextFun(request)


    return render(request, "portfolio/programacaoWeb.html", context)

portfolio/templates/portfolio/beMyBe.html
{% extends 'portfolio/layout.html' %}

{% block content %}

{% load static %}


<div class ="beMyBe_container">

    <div class =
        <div class="profile-image">
            <img src="{% static 'DuarteChen.png' %}" alt="Duarte Chen">
        </div>
        <h1>Duarte Chen</h1>
        <p>Estudante de Engenharia Informática</p>
        <p>(+351) 936 099 274 · duartechen@gmail.com · a22203153@alunos.ulusofona.pt</p>

        <div class="content">
            <div class="left">
                <section class="education">
                    <h2 class="section-title">Formação Académica</h2>
                    <p>2022 - Presente | Universidade Lusófona</p>
                    <p>Licenciatura em Engenharia Informática</p>
                    <ul>
                        <li>Fundamentos de Programação - Kotlin (17 val.)</li>
                        <li>Sistemas Digitais (14 val.)</li>
                        <li>Algoritmia e Estrutura de Dados - Java (atualmente)</li>
                        <li>Linguagens de Programação I - C (14v.)</li>
                        <li>Arquitetura de Computadores - Assembly (15v.)</li>
                    </ul>
                    <p>2018 | Universidade Católica Portuguesa</p>
                    <p>Mestrado Integrado em Teologia</p>
                    <ul>
                        <li>Aluno do Mestrado Integrado de Teologia</li>
                        <li>Desenvolvimento de pensamento teológico e filosófico em paralelo com a experiência no seminário.</li>
                    </ul>
                </section>
                <section class="skills">
                    <h2 class="section-title">Competências</h2>
                    <ul>
                        <li>Kotlin</li>
                        <li>Java</li>
                        <li>C</li>
                    </ul>
                </section>
                <section class="interests">
                    <h2 class="section-title">Interesses</h2>
                    <ul>
                        <li>Campismo</li>
                        <li>Natureza</li>
                        <li>Livros</li>
                        <li>Desporto</li>
                    </ul>
                </section>
            </div>
            <div class="right">
                <section class="experience">
                    <h2 class="section-title">Percurso Profissional</h2>
                    <ul>
                        <li>
                            <span>CGI Ambassador | 2022 - Presente</span>
                            Colaboração com atividades da empresa em iniciativas universitárias. Participação no estágio de verão de 2023.
                        </li>
                        <li>
                            <span>IKEA Loures | 2022 Marçoo - Maio</span>
                            Colaborador no balcão de serviços. Processamento e gestão de encomendas online com rotura de stock em loja. Relação com o cliente para a contratação de serviços, maioritariamente com serviços de transporte.
                        </li>
                        <li>
                            <span>Albano Almeida Lda.</span>
                            Envolvimento na empresa familiar no atendimento ao público e gestão e processamento de devoluções tanto em loja como em armazém.
                        </li>
                    </ul>
                </section>
                <section class="experience">
                    <h2 class="section-title">Experiências</h2>
                    <ul>
                        <li>
                            <span>2022 Outubro - 2024 Maio | NEC - Universidade Lusófona</span>
                            Fundador do núcleo de estudantes católicos da Universidade Lusófona. Organização de projetos. Angariação de estudantes.
                        </li>
                        <li>
                            <span>2022 - 2023 | JMJ Lisboa 2023</span>
                            Voluntário no Comité Organizador Local da JMJ Lisboa 2023, no Departamento da Pastoral e no Departamento de Comunicação, a partir de junho. Gestão e acreditação de jornalistas e órgãos de comunicação social. Criação e gestão do Parque do Perdão e de todas as estruturas que integraram o mesmo.
                        </li>
                        <li>
                            <span>2017 - 2022 | Seminário do Patriarcado de Lisboa</span>
                            Envolvimento em projetos de voluntariado com periféricos sócio, económicos. Envolvimento em vários projetos junto ao Patriarcado de Lisboa. Animador de grupos de jovens no Pré-Seminário de Lisboa. Equipar presépios pelas celebrações Patriarcais.
                        </li>
                    </ul>
                </section>
            </div>
        </div>
</div>






{% endblock %}

portfolio/templates/portfolio/contacto.html
{% extends 'portfolio/layout.html' %}

{% block content %}
<div class="login-wrapper">
    <div class="login-container" id="contactBox">
        <h2>Pedido de Contacto</h2>
        <form method="post" action="{% url 'portfolio:contacto' %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_email">Email</label>
                {{ form.email }}
            </div>
            <div class="form-group">
                <label for="id_name">Nome</label>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="id_text">Mensagem</label>
                {{ form.text }}
            </div>
            <button type="submit" id="loginButton">Enviar</button>
        </form>
    </div>
</div>
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    {% load embed_video_tags %}

    <title>Duarte Chen</title>
    <link rel="icon" type="image/x-icon" href="{% static 'DuarteChen.png' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=New+Rocker&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="./node_modules/@dschen/slidy/lib/styles/styles.css">







    <link rel="stylesheet" href="{% static 'portfolio/css/resetCSS.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/cv.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/estilos.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/subject.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/login.css' %}">

    <link rel="stylesheet" href="{% static 'bands/css/bands_styles.css' %}">


    <script src="{% static 'portfolio/js/events.js' %}"></script>

</head>
<body>
    <!Header>
    <header class="header">
        <div class="container header-container">
          <div class="header-info">
            <a href="{% url 'portfolio:portfolio' %}" id = "homebutton">
                <span class="info-name">
                    Duarte Chen
                </span>
            </a>
            <div class="info-description">
              <span>Estudante - Universidade Lusófona</span>
              <span>Licenciatura em Engenharia Informática</span>
            </div>
          </div>

            <nav class="header-nav">
                <a href = "{% url 'bands:band_list_recurso' %}">Recurso</a>
                <a href = "{% url 'portfolio:pwView' %}">PW</a>
                <a href="https://github.com/DuarteChen/a22203153-projeto-pw" onclick="window.open(this.href, '_blank');return false;">Github</a>
                <a href="{% url 'portfolio:contacto' %}">Contacto</a>
                <a {% if request.user.is_authenticated %} href="{% url 'portfolio:userView' %}" {% else %} href="{% url 'portfolio:login' %}" {% endif %} id = "loginButtonNav">{% if request.user.is_authenticated %}{{ username }}{% else %}Login{% endif %}</a>
            </nav>



          <div class="header-nav_mobile">
            <button type="button" class="menu_toggle" id="menu_toggle" >
              <i id="menu_toggle" class="menu_toggle fa-solid fa-bars"></i>

            </button>

            <nav id="menu_navigation">
                <a {% if request.user.is_authenticated %} href="{% url 'portfolio:userView' %}" {% else %} href="{% url 'portfolio:login' %}" {% endif %}>{% if request.user.is_authenticated %}{{ username }}{% else %}Login{% endif %}</a>
                <a href="https://github.com/DuarteChen/a22203153-projeto-pw" onclick="window.open(this.href, '_blank');return false;">Github</a>
                <a href="{% url 'portfolio:contacto' %}">Contacto</a>
                <a href = "{% url 'portfolio:pwView' %}">PW</a>
                <a href = "{% url 'bands:band_list_recurso' %}">Recurso</a>

            </nav>

          </div>
        </div>
  </header>
        <!Main>
    <main>
        {% block content %}
        {% endblock %}
    </main>

    <!Footer>
    <footer>

        <p>© {{ anoAtual}} Duarte Chen</p>
        <ul class="social-icons">
            <li><a href="https://www.linkedin.com/in/duartechen/" target="_blank"><i class="fab fa-linkedin"></i></a></li>
            <li><a href="https://github.com/DuarteChen" target="_blank"><i class="fab fa-github"></i></a></li>
            <li><a href="https://www.instagram.com/duartenuno_schen/" target="_blank"><i class="fab fa-instagram"></i></a></li>
            <li><a href="https://www.facebook.com/DuarteChen" target="_blank"><i class="fab fa-facebook"></i></a></li>
        </ul>

        <button id="purpleButton">Purple Theme</button>

    </footer>
</body>
</html>

portfolio/templates/portfolio/portfolio.html
{% extends 'portfolio/layout.html' %}

{% block content %}

{% load static %}

<section class="welcome" >
  <div class="container welcome-container" id = "landing_welcome">
    <div class="welcome-info">
      <h2 class="title">Olá!</h2>
      <div class = "subtitleContainer">
        <span class="subtitle">Sou o </span>
        <div class="container_name">
            <span>D</span><span>u</span><span>a</span><span>r</span><span>t</span><span>e</span><span> </span><span>C</span><span>h</span><span>e</span><span>n</span>
        </div>
      </div>
      <p class="description">Sou estudante da Licenciatura em Engenharia Informática na Universidade Lusófona.</p>
      <div class="group-buttons">
        <a href="#aboutMe" class="button_enfatizado" id = "aboutMeSection">Get to know MeByMe</a>
        <a href="#cursos" id = "universidadeSection">Universidade</a>
      </div>
    </div>
      <img class="welcome-thumbnail" src="{% static 'DuarteChen.png' %}" alt="Duarte Chen"/>
    </div>
</section>





<section class="welcome aboutMe" id="aboutMe">
    <div class="container welcome-container aboutMe_container">

        <div class ="generalInfo">

            <img id="jumping" src="{% static 'duartejumping.png' %}" alt="Duarte Chen"/>

            <div class="myDescriptions">
                <span class= "myDescriptions_nome">Duarte Chen</span>


                <span class = "descricao">Sou um jovem estudante apaixonado pela aventura, com um fascínio inabalável pela programação e pela complexidade do mundo que nos rodeia.
                                        <br>Desde pequeno que sou curioso e sempre gostei imenso de desvendar os segredos da tecnologia e, sobretudo, as suas valências.
                                        <br>Anseio por aprender cada vez mais e por me superar a mim próprio.</span>
                <span class = "descricao aspiracao">Anseio por chegar aos pícaros da felicidade!</span>
            </div>
        </div>

    </div>
</section>








<section class="welcome courses" id="cursos">

  <div class="welcome-container container">

<div class="year_and_subjects_Container">


        {% for year in "123" %}

        <div class = "year_and_subjects">
                <div class = "universityYear">
                    <h2>{{ year }}º Ano</h2>
                </div>
                <div class = "subjectsContainer">
                    <ul>
                        {% for cadeira in subjects %}
                            {% if cadeira.year|stringformat:"i" == year %}
                                <li>
                                    <a href="{% url 'portfolio:subjectView' cadeira.id %}">{{ cadeira.name }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}
                    </ul>
                </div>

            </div>
        {% endfor %}
</div>

        <div class = "year_and_subjects_mobileContainer">
        {% for year in "123" %}

                <div class = "year_and_subjects_mobile">

                    <div class = "universityYear">
                        <h2>{{ year }}º Ano</h2>
                    </div>
                    <div class = "subjectsContainer">
                        <ul>
                            {% for cadeira in subjects %}
                                {% if cadeira.year|stringformat:"i" == year %}
                                    <li>
                                        <a href="{% url 'portfolio:subjectView' cadeira.id %}">{{ cadeira.name }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                </div>


        {% endfor %}
            </div>



    </div>

</section>

<section class="welcome" id = "welcomeSection_WebAPP">
    <div class="container welcome-container" id = "webAppsContainer">

        <h2 class="title" id = "webappsTitle">My Webapp's</h2>
        <div class="slideshow-container">

            <div class="mySlides fade">
                <div id = "webAPPContainer" class="band_itemDetails">
                    <a href = "{% url 'bands:band_list' %}" id = "bandsButton">
                        <img class="webapp_image" src="{% static 'portfolio/BandsInWebScreen.png' %}" alt="Bands in Web - Web App">
                    </a>
                </div>
            </div>

            <div class="mySlides fade">
                <div id = "webAPPContainer" class="band_itemDetails">
                    <a href = "{% url 'meteo:previsao' %}" id = "meteoButton">
                        <img class="webapp_image" src="{% static 'portfolio/MeteoInWebScreen.png' %}" alt="Bands in Web - Web App">
                    </a>
                </div>
            </div>

            <div class="mySlides fade">
                <div id = "webAPPContainer" class="band_itemDetails">
                    <a href = "{% url 'jornalOnline:article_list' %}">
                        <img class="webapp_image" src="{% static 'portfolio/JornalInWebScreen.png' %}" alt="JornalOnline - Web App">
                    </a>
                </div>
            </div>


            <a class="prev" onclick="plusSlides(-1)" id = "webAppsButtonNext">&#10094;</a>
            <a class="next" onclick="plusSlides(1)">&#10095;</a>

        </div>
    </div>
</section>

{% endblock %}

portfolio/templates/portfolio/programacaoWeb.html
{% extends 'portfolio/layout.html' %}
{% load embed_video_tags %}
{% block content %}
<div class="login-wrapper" id ="pwLoginWraper">
    <div class="login-container" id ="pwbox">
        <h2>Apresentação do meu Website</h2>

        <p>Esta página elenca as capacidades que desenvolvi ao deste projeto, com uma descrição de cada uma das webapps.</p>

        <ul>
            <p class="enfaseDePontos primeiro_enfaseDePontos">Portfolio:</p>
            <li class="textoDePontos">
                É uma "vitrine digital" do trabalho realizado durante o curso da cadeira de Programação Web.
                Funciona como um hub central para as todas as páginas do projeto.
            </li>
            <p class="enfaseDePontos">Página das Bandas:</p>
            <li class="textoDePontos">
                Apresenta uma coleção de álbuns e músicas.
                Demonstra competência na criação de aplicações web dinâmicas e interativas com Python e Django. Para mim é especialmente significativa na modelação de dados em Django.
            </li>
            <p class="enfaseDePontos">Página do Curso:</p>
            <li class="textoDePontos">
                Oferece informações abrangentes sobre o meu percurso de Engenharia Informática.
                Aborda disciplinas, conteúdos programáticos e projetos desenvolvidos.
            </li>
            <p class="enfaseDePontos">Página do Blog:</p>
            <li class="textoDePontos">
                Procura criar uma comunidade de utilizadores pela partilha de artigos de variados temas.
                Promove a troca de conhecimentos e experiências entre a toda a comunidade.
            </li>
            <p class="enfaseDePontos">Página de Meteorologia:</p>
            <li class="textoDePontos">
                Utiliza uma API desenvolvida a partir do IPMA.
                Fornece informações meteorológicas de maneira acessível e envolvente.
                Demonstra habilidades na integração de APIs externas e na criação de serviços personalizados.
            </li>
            <p class="enfaseDePontos">Página de Login:</p>
            <li class="textoDePontos">
                Oferece aos usuários a possibilidade de acederem e interagir com todas as páginas do projeto.
                Possui recursos de registo local e com uma conta Google.
                Garante uma experiência de usuário confiável e segura.
            </li>
        </ul>
    </div>


    <div class="login-container" id ="pwbox">

        <p class="enfaseDePontos primeiro_enfaseDePontos">Tecnologias Utilizadas:</p>
        <ul>
            <li class="textoDePontos">Python</li>
            <li class="textoDePontos">Django</li>
            <li class="textoDePontos">HTML</li>
            <li class="textoDePontos">CSS</li>
            <li class="textoDePontos">JavaScript</li>
        </ul>
    </div>



    <div class="login-container" id ="pwbox">

        <p class="enfaseDePontos primeiro_enfaseDePontos">Habilidades Demonstradas:</p>
        <ul>
            <li class="textoDePontos">Desenvolvimento de aplicações web dinâmicas e interativas.</li>
            <li class="textoDePontos">Integração de APIs externas.</li>
            <li class="textoDePontos">Criação de serviços personalizados.</li>
            <li class="textoDePontos">Compromisso com a excelência acadêmica e a inovação tecnológica.</li>
            <li class="textoDePontos">Paixão pela Engenharia Informática.</li>
        </ul>
    </div>


    <div class="login-container" id ="pwbox">

        <p class="enfaseDePontos primeiro_enfaseDePontos">Vídeos de Apresentação</p>
        {% for i in videos %}
        {% video i.video %}
        {% endfor %}




    </div>
</div>
{% endblock %}