bands/urls.py
from django.urls import path
from .views import *

app_name = "bands"


urlpatterns = [
    path('', band_list, name='band_list'),

    path('recurso/', band_list_recurso, name='band_list_recurso'),

    path('musics/json/', musicsJson, name='musicsJson'),

    path('<int:band_id>/', band_detail, name='band_detail'),

    path('add_band/', add_band, name='add_band_form'),
    path('<int:band_id>/add_album/', add_album, name='add_album_form'),

    path('album/<int:album_id>/', album_detail, name='album_detail'),

    path('album/<int:album_id>/add_music/', add_music, name='add_music'),

    path('music/<int:music_id>/', music_detail, name='music_detail'),
]

meteo/urls.py
from django.urls import path
from . import views

app_name = "meteo"

urlpatterns = [


    path('previsao/', views.cidades, name='previsao'),
    path('previsao/json/', views.cidadesJson, name='previsaoJson'),


]

portfolio/urls.py
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('', views.portfolio_view, name="portfolio"),

    path('contacto/', views.contacto_view, name="contacto"),

    path('pw/', views.programacaoWeb, name="pwView"),

    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name="logout"),
    path('registo/', views.registo_view, name="registo"),

    path('user/', views.user_view, name="userView"),
    path('autenticacao/login/', views.user_view),

    path('subject/<int:subjectId>/', views.subject_view, name="subjectView"), #href="{% url 'subjectView' cadeira.id %}"


]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('meteo/', include('meteo.urls')),

    path('bands/', include('bands.urls')),

    path('', include('portfolio.urls'), name='portfolio'),

    path('accounts/', include('allauth.urls')),

    path('jornalOnline/', include('jornalOnline.urls')),

]

meteo/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django import forms
from datetime import date
import requests

class CityForm(forms.Form):
    idCidade = forms.ChoiceField(label='Cidade', choices=[], required=True)

def cidadesJson(request):
    url_previsao_base = "http://api.ipma.pt/open-data/forecast/meteorology/cities/daily/"
    url_classes_tempo = "http://api.ipma.pt/open-data/weather-type-classe.json"
    url_cidades = "https://api.ipma.pt/open-data/distrits-islands.json"

    resposta_cidades = requests.get(url_cidades)
    dados_cidades = None
    cidades = {}
    if resposta_cidades.status_code == 200:
        dados_cidades = resposta_cidades.json()
        if dados_cidades and 'data' in dados_cidades:
            for cidade in dados_cidades['data']:
                id = cidade.get('globalIdLocal')
                nome = cidade.get('local')
                cidades[id] = nome

    form = CityForm(request.POST or None)
    form.fields['idCidade'].choices = [(id, nome) for id, nome in cidades.items()]

    if request.method == 'POST' and form.is_valid():
        idCidade = form.cleaned_data.get('idCidade')
        url_previsao = f"{url_previsao_base}{idCidade}.json"
    else:

        url_previsao = f"{url_previsao_base}1110600.json"

    resposta_previsao = requests.get(url_previsao)
    resposta_classes = requests.get(url_classes_tempo)

    dados_previsao = resposta_previsao.json() if resposta_previsao.status_code == 200 else None
    dados_classes = resposta_classes.json() if resposta_classes.status_code == 200 else None

    contexto = {}

    if dados_previsao and 'data' in dados_previsao:
        nome_cidade = cidades[dados_previsao['globalIdLocal']]

        previsao_hoje = dados_previsao['data'][0]
        id_weather_type = previsao_hoje.get('idWeatherType')
        descricao_tempo = 'Não foi possível obter a previsão do tempo.'

        if id_weather_type and dados_classes:
            for dado in dados_classes['data']:
                if id_weather_type == dado.get('idWeatherType'):
                    descricao_tempo = dado.get('descWeatherTypePT')

        padded_number = str(id_weather_type).zfill(2) if id_weather_type else None
        icon_url = f"/static/meteo/w_ic_d_{padded_number}anim.svg" if id_weather_type else None

        previsoes = []
        for previsao in dados_previsao['data'][1:5]:
            id_weather_type = previsao.get('idWeatherType')
            padded_number = str(id_weather_type).zfill(2) if id_weather_type else None
            icon_url = f"/static/meteo/w_ic_d_{padded_number}anim.svg" if id_weather_type else None

            descricao_tempo = 'Não foi possível obter a previsão do tempo.'
            if dados_classes:
                for dado in dados_classes['data']:
                    if id_weather_type == dado.get('idWeatherType'):
                        descricao_tempo = dado.get('descWeatherTypePT')

            previsoes.append({
                'data': previsao.get('forecastDate'),
                'temperatura_minima': previsao.get('tMin', 'N/A'),
                'temperatura_maxima': previsao.get('tMax', 'N/A'),
                'descricao_tempo': descricao_tempo,
                'icon_url': icon_url
            })

        contexto = {
            'cidade': nome_cidade,
            'temperatura_minima': previsao_hoje.get('tMin', 'N/A'),
            'temperatura_maxima': previsao_hoje.get('tMax', 'N/A'),
            'data': date.today().strftime('%d/%m/%Y'),
            'descricao_tempo': descricao_tempo,
            'iconUrl': icon_url,
            'previsoes': previsoes,
        }

    return JsonResponse(contexto)














def cidades(request):
    url_previsao_base = "http://api.ipma.pt/open-data/forecast/meteorology/cities/daily/"
    url_classes_tempo = "http://api.ipma.pt/open-data/weather-type-classe.json"
    url_cidades = "https://api.ipma.pt/open-data/distrits-islands.json"

    resposta_cidades = requests.get(url_cidades)
    dados_cidades = None
    cidades = {}
    if resposta_cidades.status_code == 200:
        dados_cidades = resposta_cidades.json()
        if dados_cidades and 'data' in dados_cidades and len(dados_cidades['data']) > 0:
            for cidade in dados_cidades['data']:
                id = cidade.get('globalIdLocal')
                nome = cidade.get('local')
                cidades[id] = nome

    if request.method == 'POST':
        form = CityForm(request.POST)
        form.fields['idCidade'].choices = [(id, nome) for id, nome in cidades.items()]
        if form.is_valid():
            idCidade = form.cleaned_data.get('idCidade')
            url_previsao = url_previsao_base + str(idCidade) + ".json"
        else:
            return HttpResponse("Invalid form submission.")
    else:
        form = CityForm()
        form.fields['idCidade'].choices = [(id, nome) for id, nome in cidades.items()]
        url_previsao = url_previsao_base + "1110600.json"  # Lisbon default

    resposta_previsao = requests.get(url_previsao)
    resposta_classes = requests.get(url_classes_tempo)

    dados_previsao = None
    dados_classes = None
    contexto = {}

    if resposta_previsao.status_code == 200:
        dados_previsao = resposta_previsao.json()

    if resposta_classes.status_code == 200:
        dados_classes = resposta_classes.json()

    if dados_previsao and 'data' in dados_previsao and len(dados_previsao['data']) > 0:


        nome_cidade = cidades[dados_previsao['globalIdLocal']]


        previsao_hoje = dados_previsao['data'][0]
        id_weather_type = previsao_hoje.get('idWeatherType', None)
        descricao_tempo = 'Não foi possível obter a previsão do tempo.'

        if id_weather_type and dados_classes:
            for dado in dados_classes['data']:
                if id_weather_type == dado.get('idWeatherType', None):
                    descricao_tempo = dado.get('descWeatherTypePT')

        padded_number = str(id_weather_type).zfill(2) if id_weather_type else None
        icon_url = f"/static/meteo/w_ic_d_{padded_number}anim.svg" if id_weather_type else None

    previsoes = []
    for previsao in dados_previsao['data'][1:5]:
        id_weather_type = previsao.get('idWeatherType', None)
        padded_number = str(id_weather_type).zfill(2) if id_weather_type else None
        icon_url = f"/static/meteo/w_ic_d_{padded_number}anim.svg" if id_weather_type else None

        descricao_tempo = 'Não foi possível obter a previsão do tempo.'
        for dado in dados_classes['data']:
            if id_weather_type == dado.get('idWeatherType', None):
                descricao_tempo = dado.get('descWeatherTypePT')

        previsoes.append({
            'data': previsao.get('forecastDate'),
            'temperatura_minima': previsao.get('tMin', 'N/A'),
            'temperatura_maxima': previsao.get('tMax', 'N/A'),
            'descricao_tempo': descricao_tempo,
            'icon_url': icon_url
        })


        contexto = {
            'cidade': nome_cidade,
            'temperatura_minima': previsao_hoje.get('tMin', 'N/A'),
            'temperatura_maxima': previsao_hoje.get('tMax', 'N/A'),
            'data': date.today().strftime('%d/%m/%Y'),
            'descricao_tempo': descricao_tempo,
            'iconUrl': icon_url,
            'cidades': cidades,
            'form': form,
            'previsoes': previsoes,
        }

    return render(request, 'meteo/todayLisbon.html', contexto)

meteo/templates/meteo/todayLisbon.html
<html lang="pt">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Previsão Meteorológica</title>
    <link rel="icon" type="image/x-icon" href="{% static '{{ iconUrl }}' %}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="{% static 'meteo/css/weather.css' %}">
    <script src="{% static 'meteo/js/events.js' %}"></script>
</head>

<body>
<div class = "backAndWeather">
    <a href="{% url 'portfolio:portfolio' %}" class="back-button" id = "meteobackbutton">
            <i class="fas fa-arrow-left"></i> Back
    </a>

    <div class="weather_container">

        <a href="{% url 'meteo:previsaoJson' %}" class="back-button" id = "meteobackbutton">json</a>

        <div class="citySelectorContainer">
            <label for="citySelector">Cidade:</label>
            <form method="post" action="{% url 'meteo:previsao' %}">
                {% csrf_token %}
                {{ form.idCidade }}
                <button type="submit">Atualizar</button>
            </form>
        </div>

        <div class="previsoes">
            <div class="previsao">
                <h1>{{ cidade }}</h1>
                <h2>{{ data }}</h2>
                <p>Temperatura Mínima: {{ temperatura_minima }}°C</p>
                <p>Temperatura Máxima: {{ temperatura_maxima }}°C</p>
                <p>{{ descricao_tempo }}</p>
                <img id="iconeTempo" src="{{ iconUrl }}" alt="Ícone do Tempo">
            </div>
            <div class="proximosDias">
                <h2>Previsão para os Próximos Dias</h2>
                <div class="cincoDias_container">
                    {% for previsao in previsoes %}
                        <div class="cincoDias_info">
                            <p class = "date">{{ previsao.data }}</p>
                            <p>Min: {{ previsao.temperatura_minima }}°C</p>
                            <p>Max: {{ previsao.temperatura_maxima }}°C</p>

                            <img src="{{ previsao.icon_url }}" alt="Ícone do Tempo">
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </div>


</div>





</body>
</html>