bands/urls.py
from django.urls import path
from .views import *

app_name = "bands"


urlpatterns = [
    path('', band_list, name='band_list'),

    path('recurso/', band_list_recurso, name='band_list_recurso'),

    path('musics/json/', musicsJson, name='musicsJson'),

    path('<int:band_id>/', band_detail, name='band_detail'),

    path('add_band/', add_band, name='add_band_form'),
    path('<int:band_id>/add_album/', add_album, name='add_album_form'),

    path('album/<int:album_id>/', album_detail, name='album_detail'),

    path('album/<int:album_id>/add_music/', add_music, name='add_music'),

    path('music/<int:music_id>/', music_detail, name='music_detail'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('meteo/', include('meteo.urls')),

    path('bands/', include('bands.urls')),

    path('', include('portfolio.urls'), name='portfolio'),

    path('accounts/', include('allauth.urls')),

    path('jornalOnline/', include('jornalOnline.urls')),

]

bands/models.py
from django.db import models

class Band(models.Model):
    band_name = models.CharField(max_length=50)
    start_date = models.IntegerField()
    description = models.TextField()

    ROCK = 1
    METAL = 2
    POP = 3
    BLUES = 4
    JAZZ = 5
    FOLK = 6
    RAP = 7
    TIPO_CHOICES = [
        (ROCK, "Rock"),
        (METAL, "Metal"),
        (POP, "Pop"),
        (BLUES, "Blues"),
        (JAZZ, "Jazz"),
        (FOLK, "Folk"),
        (RAP, "Rap"),
    ]

    music_type = models.IntegerField(choices=TIPO_CHOICES, default=ROCK)
    band_image = models.ImageField(upload_to='bands/', blank=True)

    def __str__(self):
        return f'{self.band_name} - {self.start_date}, {self.get_music_type_display()}'


class BandMember(models.Model):
    name = models.CharField(max_length=50)
    birth_date = models.IntegerField("Birth Date")
    musician_image = models.ImageField(upload_to='musicians/', blank=True)
    band = models.ForeignKey(Band, on_delete=models.CASCADE, related_name='members')


    def __str__(self):
        return f'{self.name}'


class Music(models.Model):
    music_name = models.CharField(max_length=50)
    writer = models.ForeignKey(BandMember, on_delete=models.CASCADE, related_name='musics', null=True, blank=True)
    release_date = models.IntegerField()
    lyrics = models.TextField()

    def __str__(self):
        return f'{self.music_name} - {self.release_date}'


class Album(models.Model):
    album_name = models.CharField(max_length=50)
    album_release_date = models.IntegerField(blank=True)
    musics = models.ManyToManyField(Music, related_name='albums')
    band = models.ForeignKey(Band, on_delete=models.CASCADE, related_name='albums')

    def __str__(self):
        return f'{self.album_name} - {self.album_release_date}'

bands/forms.py
from django import forms
from .models import *

class BandForm(forms.ModelForm):
    class Meta:
        model = Band
        fields = ['band_name', 'start_date', 'description', 'music_type', 'band_image']


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ['album_name', 'album_release_date', 'band']

class MusicForm(forms.ModelForm):
    class Meta:
        model = Music
        fields = ['music_name', 'release_date', 'lyrics']

bands/views.py
from django.shortcuts import render, redirect
from .models import *
from datetime import datetime
from .forms import *
from django.http import HttpResponse, JsonResponse





'''
Função geral para rederização de todas as páginas ------------------------------
'''
def contextFun(request):
    username = request.user.username if request.user.is_authenticated else 'Guest'

    context = {
        'anoAtual' : datetime.today().year,
        'username': username
    }

    return context

'''
Bands views --------------------------------------------------------------------
'''

def band_list(request):
    bands = Band.objects.all()

    context = contextFun(request)
    context['bands'] = bands
    return render(request, 'bands/band_list.html', context)




def band_list_recurso(request):
    bands = Band.objects.order_by('band_name')
    bands = Band.objects.annotate(num_albums=models.Count('albums')).order_by('-num_albums')

    context = contextFun(request)
    context['bands'] = bands
    return render(request, 'bands/band_list_recurso.html', context)





def band_detail(request, band_id):
    band = Band.objects.get(id=band_id)

    context = contextFun(request)
    context['band'] = band
    return render(request, 'bands/band_detail.html', context)




def add_band(request):
    if request.method == 'POST':
        form = BandForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bands:band_list')
    else:
        form = BandForm()

    context = contextFun(request)
    context['form'] = form

    return render(request, 'bands/add_band.html', context)


def add_album(request, band_id):
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('bands:band_detail', band_id=band_id)
    else:
        form = AlbumForm(initial={'band': band_id})

    context = contextFun(request)
    context['form'] = form
    return render(request, 'bands/add_album.html', context)


def album_detail(request, album_id):

    album = Album.objects.get(pk=album_id)


    context = contextFun(request)
    context['album'] = album

    return render(request, 'bands/album_detail.html', context)

def add_music(request, album_id):
    album = Album.objects.get(pk=album_id)

    if request.method == 'POST':
        form = MusicForm(request.POST)
        if form.is_valid():
            music_name = form.cleaned_data['music_name']
            release_date = form.cleaned_data['release_date']
            lyrics = form.cleaned_data['lyrics']


            new_music = Music.objects.create(
                music_name=music_name,
                release_date=release_date,
                lyrics=lyrics,
            )


            album.musics.add(new_music)
            album.save()


            return redirect('bands:album_detail', album_id=album_id)
    else:
        form = MusicForm()

    context = contextFun(request)
    context['form'] = form
    context['album_id'] = album_id

    return render(request, 'bands/add_music.html', context)


def music_detail(request, music_id):
    music = Music.objects.get(pk=music_id)

    context = contextFun(request)
    context['music'] = music

    return render(request, 'bands/music_detail.html', context)


def musicsJson(request):

    musics = Music.objects.all()

    listaMusicas = []

    for music in musics:
        music_data = {
            'id': music.id,
            'music_name': music.music_name,
            'release_date': music.release_date,
            'lyrics': music.lyrics,

        }
        listaMusicas.append(music_data)


    return JsonResponse(listaMusicas, safe=False)

bands/templates/bands/add_album.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block content %}
<div class="login-wrapper">
    <div class="login-container">
        <h1>Add a New Album</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <div class="form-group">
                <label for="{{ form.album_name.id_for_label }}">Album Name</label>
                {{ form.album_name }}
            </div>

            <div class="form-group">
                <label for="{{ form.album_release_date.id_for_label }}">Release Date</label>
                {{ form.album_release_date }}
            </div>

            <div class="form-group">
                {{ form.band.as_hidden }}
            </div>

            <button type="submit" id ="loginButton">Save</button>
        </form>
    </div>
</div>
{% endblock %}

bands/templates/bands/add_band.html
{% extends 'portfolio/layout.html' %}

{% block content %}
<div class="login-wrapper">
    <div class="login-container">
    <h1>Add a New Band</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="form-group">
            <label for="{{ form.band_name.id_for_label }}">Band Name:</label>
            {{ form.band_name }}
            {% if form.band_name.errors %}
                <div class="error">{{ form.band_name.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.start_date.id_for_label }}">Start Date:</label>
            {{ form.start_date }}
            {% if form.start_date.errors %}
                <div class="error">{{ form.start_date.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.description.id_for_label }}">Description:</label>
            {{ form.description }}
            {% if form.description.errors %}
                <div class="error">{{ form.description.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.music_type.id_for_label }}">Music Type:</label>
            {{ form.music_type }}
            {% if form.music_type.errors %}
                <div class="error">{{ form.music_type.errors }}</div>
            {% endif %}
        </div>

        <div class="form-group">
            <label for="{{ form.band_image.id_for_label }}">Band Image:</label>
            {{ form.band_image }}
            {% if form.band_image.errors %}
                <div class="error">{{ form.band_image.errors }}</div>
            {% endif %}
        </div>

        <button type="submit" id ="loginButton" >Save</button>
    </form>
</div>
</div>
{% endblock %}

bands/templates/bands/add_music.html
{% extends 'portfolio/layout.html' %}
{% load static %}

{% block content %}
<div class="login-wrapper">
    <div class="login-container">
        <h1>Add Music to Album</h1>
        <form method="post" action="{% url 'bands:add_music' album_id=album_id %}">
            {% csrf_token %}

            <div class="form-group">
                <label for="music_name">Music Name:</label>
                <input type="text" id="music_name" name="music_name" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="release_date">Release Date:</label>
                <input type="text" id="release_date" name="release_date" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="lyrics">Lyrics:</label>
                {{ form.lyrics }}
            </div>

            <button type="submit" id ="loginButton">Add Music</button>
        </form>
    </div>
</div>
{% endblock %}

bands/templates/bands/album_detail.html
{% extends 'portfolio/layout.html' %}
{% load static %}
{% block content %}
<div class="welcome" id = "bands_welcome">
    <div class="band_itemDetails">
        <h1 class = "title">{{ album.album_name }}</h2>
        <div class="band_description">
            <div class = "band_detailsDescription">
                <p>Release Date: {{ album.album_release_date }}</p>
            </div>
        </div>
    </div>

    <div class = "albumAdderButton">
        <h2 class = "albumSubTitle">Musics</h2>
        {% if user.is_authenticated and perms.bands.add_music %}
            <a href="{% url 'bands:add_music' album.id %}">
                <img id = "addNewAlbum" class="band_image" src="{% static 'bands/add_band.svg' %}" alt="Add Band">
            </a>
        {% endif %}
    </div>

    {% for music in album.musics.all %}
    <div class="band_itemDetails musicDetailsList">
        <a href="{% url 'bands:music_detail' music.id %}" class="albumTitle">{{ music.music_name }}</a>
    </div>
    {% endfor %}

</div>
{% endblock %}

bands/templates/bands/band_detail.html
{% extends 'portfolio/layout.html' %}
{% load static %}
{% block content %}
<div class="welcome container bands-detail" id = "bands_welcome">
    <div class="band_itemDetails">
        <h1 class = "title">{{ band.band_name }}</h2>
        <div class="band_description">
            {% if band.band_image %}
                <img class="band_image" id="bandImageDetails" src="{{ band.band_image.url }}" alt="{{ band.band_name }}">
            {% endif %}
            <div class = "band_detailsDescription">
                <p>Start Date: {{ band.start_date }}</p>
                <p>Music Type: {{ band.get_music_type_display }}</p>
                <p class = "big_bandDescription">{{ band.description }}</p>
            </div>
        </div>
    </div>

    <div class = "albumAdderButton">
        <h2 class = "albumSubTitle">Albums</h2>
        {% if user.is_authenticated and perms.bands.add_album %}
            <a href="{% url 'bands:add_album_form' band.id %}">
                <img id = "addNewAlbum" class="band_image" src="{% static 'bands/add_band.svg' %}" alt="Add Band">
            </a>
        {% endif %}
    </div>
    {% for album in band.albums.all %}
    <div class="band_itemDetails albumDetails">
        <a href="{% url 'bands:album_detail' album.id %}" class="albumTitle">{{ album.album_name }}</a>
    </div>
    {% endfor %}
</div>
{% endblock %}

bands/templates/bands/band_list.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block content %}
    <div class="welcome container bands" id = "bands_welcome">
        <div class="bandsList_container">
            <h1 class="title" id="bandsInWebTitle">Bands in Web</h1>
            <div class="bandsList">
                {% if user.is_authenticated and perms.bands.add_band %}
                <li class="band_item" id = "addNewBand">
                    <a href="{% url 'bands:add_band_form' %}">
                        <img class="band_image" src="{% static 'bands/add_band.svg' %}" alt="Add Band">

                    </a>
                </li>
                {% endif %}

                </li>
                {% for band in bands %}

                    <li class="band_item">
                        <a href="{% url 'bands:band_detail' band.id %}">

                            {% if band.band_image %}
                                <img class="band_image" src="{{ band.band_image.url }}" alt="{{ band.band_name }}">
                            {% endif %}
                            <div class = "bandList_description">
                                <h2 class = "description bandTitle">{{ band.band_name }}, {{ band.start_date }}</h2>

                                <p class = "small_description">{{ band.get_music_type_display }}</p>
                            </div>

                        </a>
                    </li>
                {% endfor %}

            </div>



        </div>
    </div>

{% endblock %}

bands/templates/bands/band_list_recurso.html
{% extends 'portfolio/layout.html' %}

{% load static %}

{% block content %}
    <div class="welcome container bands" id = "bands_welcome">
        <div class="bandsList_container">
            <h1 class="title" id="bandsInWebTitle">Bands in Web</h1>
            <div class="bandsList">
                {% if user.is_authenticated and perms.bands.add_band %}
                <li class="band_item" id = "addNewBand">
                    <a href="{% url 'bands:add_band_form' %}">
                        <img class="band_image" src="{% static 'bands/add_band.svg' %}" alt="Add Band">

                    </a>
                </li>
                {% endif %}

                </li>
                {% for band in bands %}

                    <li class="band_item">
                        <a href="{% url 'bands:band_detail' band.id %}">

                            {% if band.band_image %}
                                <img class="band_image" src="{{ band.band_image.url }}" alt="{{ band.band_name }}">
                            {% endif %}
                            <div class = "bandList_description">
                                <h2 class = "description bandTitle">{{ band.band_name }}, {{ band.start_date }}</h2>

                                <p class = "small_description">{{ band.get_music_type_display }}</p>
                            </div>

                        </a>
                    </li>
                    {% for album in band.albums.all  %}
                    <li class="band_item">
                        <a href="{% url 'bands:album_detail' album.id %}">

                            <div class = "bandList_description">
                                <h2 class = "description bandTitle">{{ album.album_name }}</h2>

                                <p class = "small_description">{{ album.album_release_date }}</p>
                            </div>

                        </a>
                    </li>
                    {% endfor %}
                {% endfor %}



            </div>

            {% for band in bands %}
                {% if forloop.first %}

                        <a href= "{% url 'bands:band_detail' band.id %}">Banda com mais albums</a>
                    </form>
                {% endif %}
            {% endfor %}

            <a href="{% url 'bands:musicsJson' %}" class="back-button" id = "meteobackbutton">Musics json</a>



        </div>
    </div>

{% endblock %}

bands/templates/bands/music_detail.html
{% extends 'portfolio/layout.html' %}
{% load static %}
{% block content %}
<div class="welcome" id="bands_welcome">
    <div class="band_itemDetails">
        <h1 class="title">{{ music.music_name }}</h1>
        <div class="band_description">
            <div class="band_detailsDescription">
                <p>Release Date: {{ music.release_date }}</p>

                <p class="centered-lyrics">{{ music.lyrics|linebreaksbr }}</p>
            </div>
        </div>
    </div>
</div>
{% endblock %}